service: twitter-bot

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  deploymentBucket: serverless-upload-us-east-1
  versionFunctions: false

functions:
  main:
    handler: handler.main
    description: rubychan
    timeout: 300
    memorySize: 128
    events:
      - schedule: "cron(58 2,14 * * ? *)"
    environment:
      PIGII_CONSUMER_KEY:        ${file(kms.js):kms.PIGII_CONSUMER_KEY}
      PIGII_CONSUMER_SECRET:     ${file(kms.js):kms.PIGII_CONSUMER_SECRET}
      PIGII_ACCESS_TOKEN_KEY:    ${file(kms.js):kms.PIGII_ACCESS_TOKEN_KEY}
      PIGII_ACCESS_TOKEN_SECRET: ${file(kms.js):kms.PIGII_ACCESS_TOKEN_SECRET}
