service: twitter-bot

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-east-1
  deploymentBucket: serverless-upload-us-east-1

package:
  exclude:
    - .*
    - test/
    - event.json
    - package.json

functions:
  pigii:
    handler: handler.pigii
    description: rubychan
    timeout: 300
    memorySize: 128
    events:
      - schedule: "cron(58 2,14 * * ? *)"
    environment:
      PIGII_CONSUMER_KEY:        ${file(kms.js):kms.PIGII_CONSUMER_KEY}
      PIGII_CONSUMER_SECRET:     ${file(kms.js):kms.PIGII_CONSUMER_SECRET}
      PIGII_ACCESS_TOKEN_KEY:    ${file(kms.js):kms.PIGII_ACCESS_TOKEN_KEY}
      PIGII_ACCESS_TOKEN_SECRET: ${file(kms.js):kms.PIGII_ACCESS_TOKEN_SECRET}
