service: twitter-bot-pigii

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1
  deploymentBucket: serverless-upload-ap-northeast-1
  versionFunctions: false
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter
      Resource:
        Fn::Join: [ ":", ["arn:aws:ssm", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "parameter/pigii/*"]]

functions:
  main:
    handler: handler.main
    description: rubychan cry to twitter every 12 o'clock
    timeout: 300
    memorySize: 128
    events:
      - schedule: "cron(58 2,14 * * ? *)"

resources:
  Description: rubychan cry to twitter every 12 o'clock
  Resources:
    MainLogGroup:
      Properties:
        RetentionInDays: 7

    MainEventsRuleSchedule1:
      Properties:
        Name: "${self:service}"
        Description: pigii
