service: twitter-bot-pigii

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1
  deploymentBucket: serverless-upload-ap-northeast-1
  versionFunctions: false
  iamRoleStatements:
    - Effect: Allow
      Action:
        - kms:Decrypt
      Resource: "${s3:serverless-upload-ap-northeast-1/credstash_kms_key_arn}"
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:Scan
      Resource:
        Fn::Join: [ ":", ["arn:aws:dynamodb", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "table/credential-store"]]

functions:
  main:
    handler: handler.main
    description: rubychan cry to twitter every 12 o'clock
    timeout: 300
    memorySize: 128
    events:
      - schedule: "cron(58 2,14 * * ? *)"

resources:
  Description: rubychan cry to twitter every 12 o'clock
